SAGERPNEW2018/Controllers/PackageInfoController.cs
using AdmissionSystemModel.AdmissionModel;
using Newtonsoft.Json;
using SAGERPNEW2018.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SAGERPNEW2018.Controllers
{
    public class PackageInfoController : Controller
    {
        // GET: PackageInfo
        [Authorize]
        public ActionResult Index()
        {
            StudentPackageInfo a = new StudentPackageInfo();

            DataTable dt = loadrighta();
            if (dt.Rows.Count > 0)
            {
                a.Isdelete = Convert.ToBoolean(dt.Rows[0]["Isdelete"]);
                a.IsNew = Convert.ToBoolean(dt.Rows[0]["IsNew"]);
                a.IsPrint = Convert.ToBoolean(dt.Rows[0]["IsPrint"]);
                a.Isedit = Convert.ToBoolean(dt.Rows[0]["Isedit"]);
                a.IsAsign = Convert.ToBoolean(dt.Rows[0]["Assign"]);
                if (!a.IsAsign)
                {
                    TempData["NORights"] = "You Have No Rights To Perform This Action";
                    return RedirectToAction("Index", "Home");
                }
            }
            return View(a);
        }
        [Authorize]
        public ActionResult create(StudentPackageInfo a)
        {
            DataTable dt = loadrighta();
            if (dt.Rows.Count > 0)
            {
                a.Isdelete = Convert.ToBoolean(dt.Rows[0]["Isdelete"]);
                a.IsNew = Convert.ToBoolean(dt.Rows[0]["IsNew"]);
                a.IsPrint = Convert.ToBoolean(dt.Rows[0]["IsPrint"]);
                a.Isedit = Convert.ToBoolean(dt.Rows[0]["Isedit"]);
                a.IsAsign = Convert.ToBoolean(dt.Rows[0]["Assign"]);
                if (!a.IsAsign)
                {
                    TempData["NORights"] = "You Have No Rights To Perform This Action";
                    return RedirectToAction("Index", "Home");
                }
            }

            return View(a);
        }
        [Authorize]
        public ActionResult delete(int id)
        {
            StudentPackageInfo a = new StudentPackageInfo();
            bool c = a.DeleteData(id);
            if (c)
            {
                return RedirectToAction("Index");

            }
            TempData["Dependancy"] = "This Record Using In Another Table";
            return RedirectToAction("Index");
        }
        [Authorize]
        public ActionResult Edit(string id)
        {
            string[] ID = id.Split('|');

            StudentPackageInfo a = new StudentPackageInfo();
            var oobj = a.getAlldataByID(Convert.ToInt32(ID[0]));

            if (ID[1] == "0")
            {
                a.IsView = true;
            }
            return View("create", oobj);
        }

        [Authorize]
        public ActionResult Save(StudentPackageInfo model)
        {
            int check;
            if (model.PackageID > 0)
            {
                check = check = model.UpdateData(model);
            }
            else
            {

                check = model.addata(model);
            }

            if (check > 0)
            {
                return RedirectToAction("Index");

            }
            return RedirectToAction("create", model);
        }

        public JsonResult Duplicate(string Name, int ID)
        {
            string json = "";
            var list = new StudentPackageInfo().checkDuplicate(ID, Name);
            if (list.Count() > 0)
            {
                json = " Duplicate Record Found ";
            }
            return Json(JsonConvert.SerializeObject(json), JsonRequestBehavior.AllowGet);
        }

        private DataTable loadrighta()
        {
            string[] userdata = new Login().userinfofromCookie();
            DataTable dtright = new Login().checkRightUser(" where GLUser.Userid='" + userdata[1] + "' and UserForms.Formid='30' ");
            return dtright;
        }
    }
}

SAGERPNEW2018/Views/PackageInfo/Index.cshtml
@model AdmissionSystemModel.AdmissionModel.StudentPackageInfo

@{
    ViewBag.Title = "Fee Package";
}



<div id="modals"></div>

<header class="page-header">
    <h2>@ViewBag.Title</h2>

    <div class="right-wrapper pull-right">
        <ol class="breadcrumbs">
            <li>
                <a href="index.html">
                    <i class="fa fa-home"></i>
                </a>
            </li>
            <li><span>Registration</span></li>
            <li><span>@ViewBag.Title</span></li>
        </ol>

        <a class="sidebar-right-toggle" data-open="sidebar-right"><i class="fa fa-chevron-left"></i></a>
    </div>
</header>

<!-- start: page -->
<section class="panel">
    <header class="panel-heading">
        <div class="panel-actions">
            <a href="#" class="fa fa-caret-down"></a>
            <a href="#" class="fa fa-times"></a>
        </div>

        <h2 class="panel-title">All @ViewBag.Title Data</h2>
    </header>
    <div class="panel-body">
        <div class="row">
            <div class="col-sm-6">
                <div class="mb-md">
                    @if (Model.IsNew)
                    {
                        <button type="button" id="Add" onclick="add()" class="btn btn-primary"> <i class="fa fa-plus"></i> Add New</button>
                        @* <button type="button" id="cancelll" onclick="window.history.back()" class="btn btn-primary">Cancel</button>*@
                    }

                </div>
            </div>
        </div>
        <table class="table table-bordered table-striped mb-none table-hover" id="CatTable">
            <thead>
                <tr>
                    <th>Package</th>

                    <th>Part</th>
                    <th>Admission fee</th>
                    <th>Tuition fee</th>
                    <th>Other Fee</th>
                  






                    <th width="100px">Actions</th>
                </tr>
            </thead>

            <tbody id="ProductTableID">
                @foreach (var item in Model.getAllPackages())
                {
                    <tr>



                        <td> @item.PackageTitle </td>
                        <td> @item.title </td>
                        <td> @item.AdmissionFee </td>

                        <td> @item.TiutionFee </td>
                        <td> @item.OtherFee</td>
                    

                        <td>
                            @if (Convert.ToBoolean(Model.Isedit))
                            {

                                <a href="#basicEdit" class="on-default edit-row mb-xs mt-xs mr-xs modal-with-zoom-anim" title="Edit" onclick="Edit(@item.PackageID)">
                                    <i class="fa fa-pencil"></i>

                                </a>
                            }
                            @if (Convert.ToBoolean(Model.Isdelete))
                            {
                                <a href="#basic" class="on-default edit-row mb-xs mt-xs mr-xs modal-with-zoom-anim" title="Delete" onclick="Del(@item.PackageID)">
                                    <i class="glyphicon glyphicon-trash"></i>

                                </a>
                            }
                            <a href="#" class="on-default edit-row" title="View" onclick="view(@item.PackageID)">
                                <i class="fa fa-table"></i>

                            </a>
                            @*<button class="btn btn-success btn-xs" onclick="view(@item["Voucherid"])"><span class="glyphicon glyphicon-blackboard"></span> View</button>*@
                        </td>

                    </tr>
                }
            </tbody>

        </table>
    </div>

</section>

<script>
    $(document).ready(function () {
        $("#modals").load('/CustomClasses/IndexModaling.html')
        $("#CatTable").dataTable(
               {
                   "aoColumns": [{ "bSearchable": true }, { "bSearchable": true }, { "bSearchable": true }, { "bSearchable": true }, { "bSearchable": true }, { "bSearchable": false}
                   ],
                   "bSort": true,

                   //   dom: '<"html5buttons"B>lTfgitp',
                   dom: 'Bfrtip',
                   buttons: [
                              {
                                  extend: 'copy',
                                  text: '<span class="glyphicon glyphicon-floppy-disk"></span><span><strong> Copy</strong></span>',
                                  className: 'btn btn-primary  btn-sm',

                                  title: 'Package',

                                  exportOptions: {
                                      columns: ':visible'
                                  }

                              },

                            {
                                extend: 'pdf',
                                text: '  <span class="glyphicon glyphicon-file"></span><span> PDF</strong></span>',
                                className: 'btn btn-primary  btn-sm',
                                title: 'Package',
                                orientation: 'portrait',
                                pageSize: 'A4',
                                exportOptions: {
                                    columns: ':visible'
                                },

                                customize: function (doc) {

                                    doc.styles.title = {
                                        color: 'red',
                                        fontSize: '40',
                                        // background: 'blue',
                                        alignment: 'center'
                                    }
                                },



                            },

                             {

                                 title: 'Package',
                                 text: '<span class="glyphicon glyphicon-th"></span><span><strong> Excel</strong></span>',
                                 className: 'btn btn-primary  btn-sm',
                                 orientation: 'portrait',
                                 pageSize: 'A4',
                                 extend: 'excel',
                                 footer: true,
                                 exportOptions: {
                                     columns: ':visible'
                                 }
                             },


                           {
                               extend: 'csv',

                               title: 'Package',
                               text: '<span class="	glyphicon glyphicon-list-alt"></span><span><strong> CSV</strong></span>',
                               className: 'btn btn-primary  btn-sm',
                               exportOptions: {
                                   columns: ':visible'
                               }

                           },
                         {
                             extend: 'print',
                             title: 'Package',
                             text: '<span class="glyphicon glyphicon-print"></span><span><strong> Print</strong></span>',
                             className: 'btn btn-primary  btn-sm',

                             exportOptions: { columns: ':visible' }

                         },
                         {

                             extend: 'colvis',
                             text: '<span class="glyphicon glyphicon-blackboard"></span><span><strong> Column visibility</strong></span>',
                             className: 'btn btn-primary  btn-sm',

                             //  'colvis'
                         }

                   ],
                   columnDefs: [{ targets: -1, visible: true }]
                   //paging: false
               })
          var a = '@TempData["Dependancy"]'
        if (a != "") {
            $("#basicDendent").modal('show');
        }
        })
</script>

<script>

        function add() {
            window.location.href = "/PackageInfo/create/"
        }

        var EditID = 0;
        var DeleteID = 0;
        function confirmPopupEdit()
        {
            window.location.href = "/PackageInfo/Edit/" + EditID + "|1"
        }

        function Edit(id) {
            EditID=id
        }

        function confirmPopupDelete() {
            window.location.href = "/PackageInfo/delete/" + DeleteID

        }
        function Del(id) {
            DeleteID = id
        }

        function view(id) {
            window.location.href = "/PackageInfo/Edit/" + id + "|0"

        }

</script>

SAGERPNEW2018/Views/PackageInfo/create.cshtml
@model AdmissionSystemModel.AdmissionModel.StudentPackageInfo

@{
    ViewBag.Title = "Fee Package";
}


@using (@Html.BeginForm("Save", "PackageInfo", FormMethod.Post, new { @id = "myform" }))
{



    @Html.ValidationSummary(true)

    @Html.HiddenFor(m => m.PackageID)
    if (Model.PackageID > 0)
    {
        ViewBag.Title = "Fee Package - Edit";

    }
    else
    {

        ViewBag.Title = "Fee Package - Add";


    }
    <header class="page-header">
        <h2>@ViewBag.Title</h2>

        <div class="right-wrapper pull-right">
            <ol class="breadcrumbs">
                <li>
                    <a href="index.html">
                        <i class="fa fa-home"></i>
                    </a>
                </li>
                <li><span>Registration</span></li>
                <li><span>@ViewBag.Title</span></li>
            </ol>

            <a class="sidebar-right-toggle" data-open="sidebar-right"><i class="fa fa-chevron-left"></i></a>
        </div>
    </header>


    <div class="panel">
        <!-- start: page -->
        <div class="row">
            <div class="col-md-12">


                <section class="panel">
                    <header class="panel-heading">
                        <div class="panel-actions">
                            <a href="#" class="fa fa-caret-down"></a>
                            <a href="#" class="fa fa-times"></a>
                        </div>

                        <h2 class="panel-title">Fee Package</h2>
                        <p class="panel-subtitle">
                            Form control for input Fee Package data .
                        </p>
                    </header>
                    <div class="panel-body">
                        <div class="form-group">
                            <label class="col-sm-3 control-label">Part <span class="required">*</span></label>
                            <div class="col-sm-9 ">
                                @Html.DropDownListFor(model => model.PartID, Model.getPartValue(), new {  @class = "form-control selectpicker uneditable-input " })

                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 control-label">Package Title <span class="required">*</span></label>
                            <div class="col-sm-9 ">
                                @Html.TextBoxFor(model => model.PackageTitle, new { @placeholder = "Enter title", @class = "form-control uneditable-input ", @required = "required" })

                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 control-label">Admission Fee <span class="required">*</span></label>
                            <div class="col-sm-9 ">
                                @Html.TextBoxFor(model => model.AdmissionFee, new { @placeholder = "Enter Admission fee", @class = "form-control number uneditable-input ", @required = "required" })

                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label">Tuition fee <span class="required">*</span></label>
                            <div class="col-sm-9 ">
                                @Html.TextBoxFor(model => model.TiutionFee, new { @placeholder = "Enter Tuition", @class = "form-control number uneditable-input ", @required = "required" })

                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label">Other fee <span class="required">*</span></label>
                            <div class="col-sm-9 ">
                                @Html.TextBoxFor(model => model.OtherFee, new { @placeholder = "Enter Other", @class = "form-control number uneditable-input ", @required = "required" })

                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label">Description </label>
                            <div class="col-sm-9 ">
                                @Html.TextBoxFor(model => model.description, new { @placeholder = "Enter Description", @class = "form-control  uneditable-input " })

                            </div>
                        </div>


                    </div>
                    <footer class="panel-footer">
                        <div class="row">
                            <div class="col-sm-9 col-sm-offset-3">
                                <button type="button" onclick="postform()" class="btn btn-primary">Save</button>
                                <button type="reset" class="btn btn-default" onclick="window.history.back()">Cancel</button>
                            </div>
                        </div>
                    </footer>
                </section>

            </div>

        </div>

    </div>

}

<script>



    function postform() {
        $("#myform").validate();

        var ReturnValue = true

        //if ($("#WHDesc").val() == "") {
        //    $('#WHDesc').css('border-color', 'red');
        //    ReturnValue = false;
        //    $("#WHDesc").focus();
        //}


        var Data = { Name: $('#PackageTitle').val(), ID: $("#PackageID").val() }
                $.ajax({
                    async: false,
                    url: "/StudentSubect/Duplicate",
                    data: Data,
                    success: function (data) {

                        var c = JSON.parse(data);
                        if (c != "") {
                            alert(c)
                            ReturnValue = false;
                        }
                    },
                    error: function () {
                        ReturnValue = false;
                        alert("Error")
                    }
                })


               if (ReturnValue) {

                   $("#myform").submit();
                }

            }

    $(document).ready(function () {
       // $('#Myform :input').select()

        if ('@Model.IsView' == 'True') {
            $('#myform :input').attr('disabled', true);
            $('#cancelll').attr('disabled', false);

        }

    });


</script>