SAGERPNEW2018/Controllers/GLReportsController.cs
using Newtonsoft.Json;
using AdmissionSystemModel.AdmissionModel;
using SAGERPNEW2018.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CrystalDecisions.CrystalReports.Engine;
using System.IO;
using Microsoft.Reporting.WebForms;

namespace SAGERPNEW2018.Controllers
{
    public class GLReportsController : Controller
    {
        // GET: GLReports //
        public ActionResult SessionWiseReport()
        {
            ReportModel a = new ReportModel();
            DataTable dt = loadrighta();
            if (dt.Rows.Count > 0)
            {
                a.Isdelete = Convert.ToBoolean(dt.Rows[0]["Isdelete"]);
                a.IsNew = Convert.ToBoolean(dt.Rows[0]["IsNew"]);
                a.IsPrint = Convert.ToBoolean(dt.Rows[0]["IsPrint"]);
                a.Isedit = Convert.ToBoolean(dt.Rows[0]["Isedit"]);
                a.IsAsign = Convert.ToBoolean(dt.Rows[0]["Assign"]);
                if (!a.IsAsign)
                {
                    TempData["NORights"] = "You Have No Rights To Perform This Action";
                    return RedirectToAction("Index", "Home");
                }
            }
            return View(a);
        }

        [HttpPost]
        public ActionResult SessionWiseReport(ReportModel model)
        {
            string[] userdata = new Login().userinfofromCookie();
            try
            {
                ReportDocument rptH = new ReportDocument();
                rptH.Load(Path.Combine(Server.MapPath("~/Reports"), "SessionReport.rpt"));
                var dt = new ReportModel().GetDataSessionWiseReport(model.PartID,model.SessionID);
                var host = new UriBuilder(Request.Url.Scheme, Request.Url.Host, Request.Url.Port);
                foreach (DataRow item in dt.Rows)
                {
                    item["PhotoPath"] = host + item["PhotoPath"].ToString().TrimStart('~');

                }
                rptH.Database.Tables[0].SetDataSource(dt);
                //rptH.SetDataSource();
                if (dt.Rows.Count > 0)
                {
                    
                   // rptH.SetParameterValue("image",dt.row);

                    // rptH.SetParameterValue("image", path);

                    Stream stream = rptH.ExportToStream(CrystalDecisions.Shared.ExportFormatType.PortableDocFormat);
                    return File(stream, "application/pdf", "Session Wise Report.pdf");
                }
                else
                {
                    return Content("No Data Found");

                    //  return RedirectToAction("TrailIndex", "GLReports");

                }

            }
            catch (Exception ex)
            {

                throw;
            }

        }





        public ActionResult AdmissionReport(string id , string type)
        {
            string[] userdata = new Login().userinfofromCookie();

            //  string[] response = id.Split('|');
            if (type == "0")
            {
                ReportDocument rptH = new ReportDocument();
                rptH.Load(Path.Combine(Server.MapPath("~/Reports"), "AdmissionReport.rpt"));
                var dt = new ReportModel().GetDataAdmission(id);
                rptH.Database.Tables[0].SetDataSource(dt);
                //rptH.SetDataSource();
                if (dt.Rows.Count > 0)
                {
                    var host = new UriBuilder(Request.Url.Scheme, Request.Url.Host, Request.Url.Port);

                    string path = host + dt.Rows[0]["PhotoPath"].ToString().TrimStart('~');
                    rptH.SetParameterValue("ImagePath", path);

                    Stream stream = rptH.ExportToStream(CrystalDecisions.Shared.ExportFormatType.PortableDocFormat);
                    return File(stream, "application/pdf", "Admission Information.pdf");
                }
                else
                {
                    return Content("No Data Found");

                    //  return RedirectToAction("TrailIndex", "GLReports");

                }

            }
            else
            {

                ReportDocument rptH = new ReportDocument();
                rptH.Load(Path.Combine(Server.MapPath("~/Reports"), "DetailAddmissionReport.rpt"));
                var dt = new ReportModel().GetDataAdmission(id);
                rptH.Database.Tables[0].SetDataSource(dt);
                //rptH.SetDataSource();
                if (dt.Rows.Count > 0)
                {
                    var host = new UriBuilder(Request.Url.Scheme, Request.Url.Host, Request.Url.Port);

                    string path = host + dt.Rows[0]["PhotoPath"].ToString().TrimStart('~');
                    rptH.SetParameterValue("ImageParm", path);

                    Stream stream = rptH.ExportToStream(CrystalDecisions.Shared.ExportFormatType.PortableDocFormat);
                    return File(stream, "application/pdf", "Admission Information.pdf");
                }
                else
                {
                    return Content("No Data Found");

                    //  return RedirectToAction("TrailIndex", "GLReports");

                }

            }

          

        }


        public ActionResult ChallanPrint()
        {
            ReportModel a = new ReportModel();
            DataTable dt = loadrighta();
            if (dt.Rows.Count > 0)
            {
                a.Isdelete = Convert.ToBoolean(dt.Rows[0]["Isdelete"]);
                a.IsNew = Convert.ToBoolean(dt.Rows[0]["IsNew"]);
                a.IsPrint = Convert.ToBoolean(dt.Rows[0]["IsPrint"]);
                a.Isedit = Convert.ToBoolean(dt.Rows[0]["Isedit"]);
                a.IsAsign = Convert.ToBoolean(dt.Rows[0]["Assign"]);
                if (!a.IsAsign)
                {
                    TempData["NORights"] = "You Have No Rights To Perform This Action";
                    return RedirectToAction("Index", "Home");
                }
            }
            return View(a);
        }

        [HttpPost]
        public ActionResult ChallanPrint(ReportModel a)
        {
            DataTable dt = new ReportModel().GetDataCHallan(a);
            var check=new ReportModel().GenerateChallan(a);

            ReportDocument rptH = new ReportDocument();
            rptH.Load(Path.Combine(Server.MapPath("~/Reports"), "RptChallan.rpt"));
            rptH.Database.Tables[0].SetDataSource(dt);
            //rptH.SetDataSource();
            if (dt.Rows.Count > 0)
            {
                rptH.SetParameterValue("ChallanDate", a.DateFrom);
                Stream stream = rptH.ExportToStream(CrystalDecisions.Shared.ExportFormatType.PortableDocFormat);
                return File(stream, "application/pdf", "Challan.pdf");
            }
            else
            {
                return Content("No Data Found");

                //  return RedirectToAction("TrailIndex", "GLReports");

            }

            return View(a);
        }


        //public ActionResult TrailIndex()
        //{
        //    ReportModel a = new ReportModel();
        //    DataTable dt = loadrighta(2);
        //    if (dt.Rows.Count > 0)
        //    {
        //        a.Isdelete = Convert.ToBoolean(dt.Rows[0]["Isdelete"]);
        //        a.IsNew = Convert.ToBoolean(dt.Rows[0]["IsNew"]);
        //        a.IsPrint = Convert.ToBoolean(dt.Rows[0]["IsPrint"]);
        //        a.Isedit = Convert.ToBoolean(dt.Rows[0]["Isedit"]);
        //        a.IsAsign = Convert.ToBoolean(dt.Rows[0]["Assign"]);
        //        if (!a.IsAsign)
        //        {
        //            TempData["NORights"] = "You Have No Rights To Perform This Action";
        //            return RedirectToAction("Index", "Home");
        //        }
        //    }
        //    return View(a);
        //}
        //public ActionResult Report()
        //{
        //    ReportModel a = new ReportModel();
        //    //  return new Rotativa.MVC.ActionAsPdf("Index");
        //    return new Rotativa.MVC.ActionAsPdf("PrintReport",a) { FileName = "TestActionAsPdf.pdf" };
        //}


        //public ActionResult TrailReport(string iniName)
        //{
        //    string[] userdata = new Login().userinfofromCookie();

        //    string[] response = iniName.Split('|');
        //    string where = "where   GLvMAIN.FiscalID='" + userdata[3] + "' and   GLvMAIN.Comp_Id='" + userdata[4] + "' and ";

        //    if (response[0] != "0")
        //    {
        //        where += "    FirstParentID ='" + response[0] + "' and  ";


        //    }

        //    where += " GLvMAIN.vDate  between '" + response[2] + "' and '" + response[3] + "' order by  GLvMAIN.vDate asc ";



        //    ReportDocument rptH = new ReportDocument();
        //    rptH.Load(Path.Combine(Server.MapPath("~/Reports"), "TrailReportWithlevels.rpt"));
        //    DataTable dt = new ReportModel().selectallTrail(where);
        //    rptH.SetDataSource(dt);
        //    if (dt.Rows.Count > 0)
        //    {
        //        rptH.SetParameterValue("CompanyName", dt.Rows[0]["title"]);
        //        rptH.SetParameterValue("Repoetdate", "Date From " + response[2] + " To " + response[3] + "");
        //        rptH.SetParameterValue("Address", "Address: " + dt.Rows[0]["address"] + " || Contact No: " + dt.Rows[0]["Phone"] + "  || Website: " + dt.Rows[0]["Website"] + " ");
        //        rptH.SetParameterValue("Opeartor", userdata[0]);

        //        Stream stream = rptH.ExportToStream(CrystalDecisions.Shared.ExportFormatType.PortableDocFormat);
        //        return File(stream, "application/pdf");
        //    }
        //    else
        //    {
        //        return Content("No Data Found");

        //        //  return RedirectToAction("TrailIndex", "GLReports");

        //    }

        //}


        //public ActionResult searchdataVoucherTrail(string glName,  string DateFrom, string DateTo)
        //{

SAGERPNEW2018/Views/GLReports/ChallanPrint.cshtml
@model SAGERPNEW2018.Models.ReportModel
@using AdmissionSystemModel.AdmissionModel

@{
    ViewBag.Title = "Challan Generate";
}



<header class="page-header">
    <h2>  @ViewBag.Title</h2>

    <div class="right-wrapper pull-right">
        <ol class="breadcrumbs">
            <li>
                <a href="index.html">
                    <i class="fa fa-home"></i>
                </a>
            </li>
            <li><span>System Reports</span></li>
            <li><span>  @ViewBag.Title</span></li>
        </ol>

        <a class="sidebar-right-toggle" data-open="sidebar-right"><i class="fa fa-chevron-left"></i></a>
    </div>
</header>
@using (@Html.BeginForm("ChallanPrint", "GLReports", FormMethod.Post, new { @id = "myform" }))
{

    <div class="panel">
        <!-- start: page -->
        <div class="row">
            <div class="col-md-12">


                <section class="panel">
                    <header class="panel-heading">
                        <div class="panel-actions">
                            <a href="#" class="fa fa-caret-down"></a>
                            <a href="#" class="fa fa-times"></a>
                        </div>

                        <h2 class="panel-title">@ViewBag.Title</h2>
                        <p class="panel-subtitle">
                            Form control for @ViewBag.Title data .
                        </p>
                    </header>
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-sm-3 " style="padding-right: 0px;font-size: 12px;">
                                <label> Session:</label>&nbsp;<span style="color:red;" class="error-span" id="TitleIDError"></span>
                                @Html.DropDownListFor(model => model.SessionID, new AdmissionInformation().getAllSessionValue(), new { @class = "form-control  selectpicker " })

                            </div>

                            <div class="col-sm-3" style="padding-right: 0px;font-size: 12px;">
                                <label>Part :</label>&nbsp;<span style="color:red;" class="error-span" id="TitleIDError"></span>
                                @Html.DropDownListFor(model => model.PartID, new AdmissionInformation().getPartValue(), new { @class = "form-control selectpicker " })
                            </div>

                            <div class="col-sm-3" style="padding-right: 0px;font-size: 12px;">
                                <label>Student / Roll No. :</label>&nbsp;<span style="color:red;" class="error-span" id="TitleIDError"></span>
                                @Html.DropDownListFor(model => model.AdmissionID, new AdmissionInformation().GetStudentNameList(), new { @class = "form-control selectpicker " })
                            </div>
                            <div class="col-sm-2" style="padding-right: 0px;font-size: 12px;">

                                    <label>Challan Due Date:</label>&nbsp;<span style="color:red;" class="error-span" id="ShortTitleIDError"></span>

                                    <div class='input-group date' id='datetimepicker1'>
                                        @Html.TextBoxFor(model => model.DateFrom, new { @class = "form-control form-control-sm", @readonly = "readonly" })
                                        <span class="input-group-addon">
                                            <span class="glyphicon glyphicon-calendar"></span>
                                        </span>
                                    </div>
                                </div>
@*
    <div class="col-sm-2" style="padding-right: 0px;font-size: 12px;">

        <label>Date To:</label>&nbsp;<span style="color:red;" class="error-span" id="ShortTitleIDError"></span>

        <div class='input-group date' id='datetimepicker1'>
            @Html.TextBoxFor(model => model.DateTo, new { @class = "form-control", @readonly = "readonly" })
            <span class="input-group-addon">
                <span class="glyphicon glyphicon-calendar"></span>
            </span>
        </div>
    </div>*@
                            <div class="col-sm-2" style="padding-right: 0px;font-size: 12px;">
                                @if (Model.IsPrint)
                                {
                                    <button style="margin-top: 24px;" type="submit" id="Add" class="btn  btn-success"> <span class="glyphicon glyphicon-print"></span>   Print</button>
                                }
                            </div>
                        </div>


                    </div>
                    <footer class="panel-footer">
                        <div class="row">
                            <div class="col-sm-8 ">

                            </div>
                        </div>
                    </footer>
                </section>

            </div>

        </div>

    </div>


}


<style>
    tr.group,
    tr.group:hover {
        background-color: #ddd !important;
    }
</style>



<script>



        //function viewpdf() {
        //    var id = "" + $('#GLAccountID').val() + "|" + $('#DimensionValueID').val() + "|" + $('#DateFrom').val() + "|" + $('#DateTo').val() + "  "
        //    window.open('/GLReports/csReport/?iniName=' + id + '   ', '_blank');

        //}

        $(document).ready(function () {



            $("#DateFrom").datepicker({
                format: "dd-M-yyyy",
                autoclose: true,
                todayBtn: true,
                //startDate: "2018-07-01",

                // minuteStep: 10
            });

            $("#DateFrom").datepicker("setDate", new Date());

            $("#DateTo").datepicker({

                format: "dd-M-yyyy",
                autoclose: true,
                todayBtn: true,
                //startDate: "2018-07-01",

                // minuteStep: 10
            });
            $("#DateTo").datepicker("setDate", new Date());

        });




        $('.selectpicker').selectpicker({
            liveSearch: true,
            size: 10,
            // width: 'auto',
            container: "body"

        });
</script>

SAGERPNEW2018/Views/GLReports/PrintReport.cshtml
@model SAGERPNEW2018.Models.ReportModel

@{
    ViewBag.Title = "PrintReport";
    Layout = "";
}
<div class="alert alert-success">
    
    <div class="row ">
        <div class="col-lg-12">
            <div class="panel panel-default">

                <div class="panel-heading">
                    General Legder Data
                </div>
                <div class="panel-body" style="overflow-y:auto">
                    <div>

                        <table id="ReportHeadTable" class="table table-hover table-responsive table-striped nowrap" cellspacing="0" cellpadding="1" style="width: 100%;">
                            <thead>
                                <tr @*style="background-color: #337ab7;"*@>
                                    <th>GL Account</th>
                                    <th>Dimension Type</th>
                                    <th>Dimension Value </th>
                                    <th>Narration</th>
                                    <th>Cheque No</th>
                                    <th>Cheque Date</th>
                                    <th>Dr</th>
                                    <th>Cr</th>
                                </tr>
                            </thead>


                            <tbody id="BodyTableID"></tbody>
                            @foreach (System.Data.DataRow item in Model.selectall().Rows)
                            {
                                    <tr>
                                        <td> @item["GLTitle"] </td>
                                        <td> @item["dimensionValues"] </td>
                                        <td> @item["Narration"] </td>
                                        <td> @item["ChequeNo"] </td>
                                        <td> @item["ChequeDate"] </td>
                                        <td> @item["cr"] </td>
                                        <td> @item["dr"] </td>
                                    </tr>
                            }



                        </table>

                    </div>
                    <!-- /.row (nested) -->
                </div>


                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <div class="panel panel-default">
        <div class="row panel-body">
            <div class="col-md-2" style="float:right">
                <label>Total Cr:</label>
                @Html.TextBoxFor(model => model.TotalCr, new { @class = "form-control form-control-sm", @readonly = "readonly" })

            </div>
            <div class="col-md-2 " style="float:right">
                <label>Total Dr:</label>

                @Html.TextBoxFor(model => model.TotalDr, new { @class = "form-control form-control-sm", @readonly = "readonly" })
            </div>
        </div>
    </div>
</div>

SAGERPNEW2018/Views/GLReports/SessionWiseReport.cshtml
@using AdmissionSystemModel.AdmissionModel
@model SAGERPNEW2018.Models.ReportModel

@{
    ViewBag.Title = "Session Wise Report";
}

<header class="page-header">
    <h2>  @ViewBag.Title</h2>

    <div class="right-wrapper pull-right">
        <ol class="breadcrumbs">
            <li>
                <a href="index.html">
                    <i class="fa fa-home"></i>
                </a>
            </li>
            <li><span>System Reports</span></li>
            <li><span>  @ViewBag.Title</span></li>
        </ol>

        <a class="sidebar-right-toggle" data-open="sidebar-right"><i class="fa fa-chevron-left"></i></a>
    </div>
</header>
@using (@Html.BeginForm("SessionWiseReport", "GLReports", FormMethod.Post, new { @id = "myform" }))
{

<div class="panel">
    <!-- start: page -->
    <div class="row">
        <div class="col-md-12">


            <section class="panel">
                <header class="panel-heading">
                    <div class="panel-actions">
                        <a href="#" class="fa fa-caret-down"></a>
                        <a href="#" class="fa fa-times"></a>
                    </div>

                    <h2 class="panel-title">@ViewBag.Title</h2>
                    <p class="panel-subtitle">
                        Form control for @ViewBag.Title data .
                    </p>
                </header>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-sm-3 " style="padding-right: 0px;font-size: 12px;">
                            <label> Session:</label>&nbsp;<span style="color:red;" class="error-span" id="TitleIDError"></span>
                            @Html.DropDownListFor(model => model.SessionID, new AdmissionInformation().getAllSessionValue(), new { @class = "form-control  selectpicker " })

                        </div>

                        <div class="col-sm-3" style="padding-right: 0px;font-size: 12px;">
                            <label>Part :</label>&nbsp;<span style="color:red;" class="error-span" id="TitleIDError"></span>
                            @Html.DropDownListFor(model => model.PartID, new AdmissionInformation().getPartValue(), new { @class = "form-control selectpicker " })
                        </div>

                        @*<div class="col-sm-2" style="padding-right: 0px;font-size: 12px;">

                            <label>Date From:</label>&nbsp;<span style="color:red;" class="error-span" id="ShortTitleIDError"></span>

                            <div class='input-group date' id='datetimepicker1'>
                                @Html.TextBoxFor(model => model.DateFrom, new { @class = "form-control form-control-sm", @readonly = "readonly" })
                                <span class="input-group-addon">
                                    <span class="glyphicon glyphicon-calendar"></span>
                                </span>
                            </div>
                        </div>
                        <div class="col-sm-2" style="padding-right: 0px;font-size: 12px;">

                            <label>Date To:</label>&nbsp;<span style="color:red;" class="error-span" id="ShortTitleIDError"></span>

                            <div class='input-group date' id='datetimepicker1'>
                                @Html.TextBoxFor(model => model.DateTo, new { @class = "form-control", @readonly = "readonly" })
                                <span class="input-group-addon">
                                    <span class="glyphicon glyphicon-calendar"></span>
                                </span>
                            </div>
                        </div>*@
                        <div class="col-sm-2" style="padding-right: 0px;font-size: 12px;">
                            @if (Model.IsPrint)
                            {
                                <button style="margin-top: 24px;" type="submit" id="Add" class="btn  btn-success"> <span class="glyphicon glyphicon-print"></span>   Print</button>
                            }
                        </div>
                        </div>
                
                   
                </div>
                <footer class="panel-footer">
                    <div class="row">
                        <div class="col-sm-8 ">
                         
                        </div>
                    </div>
                </footer>
            </section>

        </div>

    </div>

</div>


}


<style>
    tr.group,
    tr.group:hover {
        background-color: #ddd !important;
    }
</style>



<script>

       

        //function viewpdf() {
        //    var id = "" + $('#GLAccountID').val() + "|" + $('#DimensionValueID').val() + "|" + $('#DateFrom').val() + "|" + $('#DateTo').val() + "  "
        //    window.open('/GLReports/csReport/?iniName=' + id + '   ', '_blank');

        //}

        $(document).ready(function () {



            $("#DateFrom").datepicker({
                format: "dd-M-yyyy",
                autoclose: true,
                todayBtn: true,
                //startDate: "2018-07-01",

                // minuteStep: 10
            });

            $("#DateFrom").datepicker("setDate", new Date());

            $("#DateTo").datepicker({

                format: "dd-M-yyyy",
                autoclose: true,
                todayBtn: true,
                //startDate: "2018-07-01",

                // minuteStep: 10
            });
            $("#DateTo").datepicker("setDate", new Date());

        });




        $('.selectpicker').selectpicker({
            liveSearch: true,
            size: 10,
            // width: 'auto',
            container: "body"

        });
</script>