SAGERPNEW2018/Controllers/NavbarController.cs
using SAGERPNEW2018.Domain;
using SAGERPNEW2018.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SAGERPNEW2018.Controllers
{
    public class NavbarController : Controller
    {
        // GET: Navbar
        public ActionResult Index()
        {
            Navbar nav = new Navbar();
            var data = new Data();
          string[] user  = new Login().userinfofromCookie();
        
            Session["UserName"] = user[0];
        
            return PartialView("_Navigation", data.navbarItems().ToList());
        }
    }
}

SAGERPNEW2018/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html class="fixed">
<head>
    <title>@ViewBag.Title </title>
    <meta charset="utf-8" />
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
    @*<meta name="viewport" content="width=device-width, initial-scale=1.0">*@
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    

   
    <!-- Vendor CSS -->
    <link rel="stylesheet" href="/assets/vendor/bootstrap/css/bootstrap.css"/>
    <link rel="stylesheet" href="/assets/vendor/bootstrap-datepicker/css/datepicker3.css" />
    <link rel="stylesheet" href="/assets/vendor/font-awesome/css/font-awesome.css" />
    <link rel="stylesheet" href="/assets/vendor/magnific-popup/magnific-popup.css" />

    <!-- Specific Page Vendor CSS -->
    <link rel="stylesheet" href="/assets/vendor/jquery-ui/css/ui-lightness/jquery-ui-1.10.4.custom.css" />
    <link rel="stylesheet" href="/assets/vendor/select2/select2.css" />
    <link rel="stylesheet" href="/assets/vendor/bootstrap-multiselect/bootstrap-multiselect.css" />
    <link rel="stylesheet" href="/assets/vendor/bootstrap-tagsinput/bootstrap-tagsinput.css" />
    <link rel="stylesheet" href="/assets/vendor/bootstrap-colorpicker/css/bootstrap-colorpicker.css" />
    <link rel="stylesheet" href="/assets/vendor/bootstrap-timepicker/css/bootstrap-timepicker.css" />
    <link rel="stylesheet" href="/assets/vendor/dropzone/css/basic.css" />
    <link rel="stylesheet" href="/assets/vendor/dropzone/css/dropzone.css" />
    <link rel="stylesheet" href="/assets/vendor/bootstrap-markdown/css/bootstrap-markdown.min.css" />
    <link rel="stylesheet" href="/assets/vendor/summernote/summernote.css" />
    <link rel="stylesheet" href="/assets/vendor/summernote/summernote-bs3.css" />
    <link rel="stylesheet" href="/assets/vendor/codemirror/lib/codemirror.css" />
    <link rel="stylesheet" href="/assets/vendor/codemirror/theme/monokai.css" />

    <!-- Theme CSS -->
    <link rel="stylesheet" href="/assets/stylesheets/theme.css" />

    <!-- Skin CSS -->
    <link rel="stylesheet" href="/assets/stylesheets/skins/default.css" />
    <!-- Vendor CSS -->
    <!-- Specific Page Vendor CSS -->
    <link rel="stylesheet" href="/assets/vendor/pnotify/pnotify.custom.css" />

    <link rel="stylesheet" href="/assets/stylesheets/theme-custom.css">

   
    
    <!-- Vendor -->
    <script src="/assets/vendor/jquery/jquery.js"></script>
    <script src="/assets/vendor/jquery-browser-mobile/jquery.browser.mobile.js"></script>
    <script src="/assets/vendor/bootstrap/js/bootstrap.js"></script>
    <script src="/assets/vendor/nanoscroller/nanoscroller.js"></script>
    <script src="/assets/vendor/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>
    <script src="/assets/vendor/magnific-popup/magnific-popup.js"></script>
    <script src="/assets/vendor/jquery-placeholder/jquery.placeholder.js"></script>


    <!-- Specific Page model -->
    <script src="/assets/vendor/pnotify/pnotify.custom.js"></script>

    <!-- Theme Base, Components and Settings -->
    <!-- Examples -->
    <script src="/assets/javascripts/ui-elements/examples.modals.js"></script>
    <!-- Head Libs -->
    <script src="/assets/vendor/modernizr/modernizr.js"></script>

    <link rel="stylesheet" href="/assets/vendor/pnotify/pnotify.custom.css" />
    @*<link rel="stylesheet" href="/assets/vendor/bootstrap/css/bootstrap.css" />*@

    <style>
        a:hover {
            text-decoration: none;
        }
    </style>

</head>

<body  style="overflow-y:auto" >
    <section class="body"  >
        
            <div class="inner-wrapper">

                @Html.Action("Index", "Navbar")
                <section role="main" class="content-body" >
                    @RenderBody()
                </section>
        </div>

      
</section>
    <!-- Specific Page Vendor -->
    <script src="/assets/vendor/pnotify/pnotify.custom.js"></script>

    <!-- Examples -->
    <script src="/assets/javascripts/ui-elements/examples.modals.js"></script>

        @Styles.Render("~/Content/dataTables/dataTablesStyles")
        @Scripts.Render("~/Content/dataTables1")


    <!-- Specific Page Vendor -->
    <script src="/assets/vendor/jquery-ui/js/jquery-ui-1.10.4.custom.js"></script>
    <script src="/assets/vendor/jquery-ui-touch-punch/jquery.ui.touch-punch.js"></script>
    <script src="/assets/vendor/select2/select2.js"></script>
    <script src="/assets/vendor/bootstrap-multiselect/bootstrap-multiselect.js"></script>
    <script src="/assets/vendor/jquery-maskedinput/jquery.maskedinput.js"></script>
    <script src="/assets/vendor/bootstrap-tagsinput/bootstrap-tagsinput.js"></script>
    <script src="/assets/vendor/bootstrap-colorpicker/js/bootstrap-colorpicker.js"></script>
    <script src="/assets/vendor/bootstrap-timepicker/js/bootstrap-timepicker.js"></script>
    <script src="/assets/vendor/fuelux/js/spinner.js"></script>
    <script src="/assets/vendor/dropzone/dropzone.js"></script>
    <script src="/assets/vendor/bootstrap-markdown/js/markdown.js"></script>
    <script src="/assets/vendor/bootstrap-markdown/js/to-markdown.js"></script>
    <script src="/assets/vendor/bootstrap-markdown/js/bootstrap-markdown.js"></script>
    <script src="/assets/vendor/codemirror/lib/codemirror.js"></script>
    <script src="/assets/vendor/codemirror/addon/selection/active-line.js"></script>
    <script src="/assets/vendor/codemirror/addon/edit/matchbrackets.js"></script>
    <script src="/assets/vendor/codemirror/mode/javascript/javascript.js"></script>
    <script src="/assets/vendor/codemirror/mode/xml/xml.js"></script>
    <script src="/assets/vendor/codemirror/mode/htmlmixed/htmlmixed.js"></script>
    <script src="/assets/vendor/codemirror/mode/css/css.js"></script>
    <script src="/assets/vendor/summernote/summernote.js"></script>
    <script src="/assets/vendor/bootstrap-maxlength/bootstrap-maxlength.js"></script>
    <script src="/assets/vendor/ios7-switch/ios7-switch.js"></script>

    <!-- Theme Base, Components and Settings -->
    <script src="/assets/javascripts/theme.js"></script>

    <!-- Theme Custom -->
    <script src="/assets/javascripts/theme.custom.js"></script>

    <!-- Theme Initialization Files -->
    <script src="/assets/javascripts/theme.init.js"></script>

    <script src="/assets/javascripts/forms/examples.advanced.form.js"></script>

    <!-- Validation  Files -->
    <script src="/assets/vendor/jquery-validation/jquery.validate.js"></script>
    <script src="/assets/javascripts/forms/examples.validation.js"></script>
    <script src="/assets/vendor/select2/select2.js"></script>
    <link href="~/Content/bootstrap-select.min.css" rel="stylesheet" />
    <script src="~/Scripts/bootstrap-select.min.js"></script>
   
    <script>

        $('.number').keypress(function (event) {
            if ((event.which != 46 || $(this).val().indexOf('.') != -1) && (event.which < 48 || event.which > 57)) {
                event.preventDefault();
            }
        });

        $('.selectpicker').selectpicker({
            liveSearch: true,
            container: "body"
        });
        $('.selectpicker').selectpicker('refresh');

        $('.select').select2({
            selectOnClose: true
        });
    </script>
        @RenderSection("scripts", required: false)

</body>



</html>