SAGERPNEW2018/Controllers/GLUserController.cs
using AdmissionSystemModel.AdmissionModel;
using Newtonsoft.Json;
using SAGERPNEW2018.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SAGERPNEW2018.Controllers
{
    public class GLUserController : Controller
    {
        // GET: GLUser
        [Authorize]
        public ActionResult Index()
        {
            GLUser a = new GLUser();

            DataTable dt = loadrighta();
            if (dt.Rows.Count > 0)
            {
                a.Isdelete = Convert.ToBoolean(dt.Rows[0]["Isdelete"]);
                a.IsNew = Convert.ToBoolean(dt.Rows[0]["IsNew"]);
                a.IsPrint = Convert.ToBoolean(dt.Rows[0]["IsPrint"]);
                a.Isedit = Convert.ToBoolean(dt.Rows[0]["Isedit"]);
                a.IsAsign = Convert.ToBoolean(dt.Rows[0]["Assign"]);
                if (!a.IsAsign)
                {
                    TempData["NORights"] = "You Have No Rights To Perform This Action";
                    return RedirectToAction("Index", "Home");
                }
            }
            return View(a);
        }
        [Authorize]
        public ActionResult create(GLUser a)
        {
            DataTable dt = loadrighta();
            if (dt.Rows.Count > 0)
            {
                a.Isdelete = Convert.ToBoolean(dt.Rows[0]["Isdelete"]);
                a.IsNew = Convert.ToBoolean(dt.Rows[0]["IsNew"]);
                a.IsPrint = Convert.ToBoolean(dt.Rows[0]["IsPrint"]);
                a.Isedit = Convert.ToBoolean(dt.Rows[0]["Isedit"]);
                a.IsAsign = Convert.ToBoolean(dt.Rows[0]["Assign"]);
                if (!a.IsAsign)
                {
                    TempData["NORights"] = "You Have No Rights To Perform This Action";
                    return RedirectToAction("Index", "Home");
                }
            }

            return View(a);
        }
        [Authorize]
        public ActionResult delete(int id)
        {
            GLUser a = new GLUser();

            bool c = a.DeleteData(id);
            if (c)
            {
                return RedirectToAction("Index");

            }
            TempData["Dependancy"] = "This Record Using In Another Table";
            return RedirectToAction("Index");
        }
        [Authorize]
        public ActionResult Edit(string id)
        {
            string[] ID = id.Split('|');

            GLUser a = new GLUser();
            var obj= a.getAlldataByID(Convert.ToInt32(ID[0]));



            if (ID[1] == "0")
            {
                a.IsView = true;
            }
            return View("create", obj);
        }

        [Authorize]
        public ActionResult Save(GLUser model)
        {
            int check;
            if (model.Userid > 0)
            {
                check = check = model.UpdateData(model);
            }
            else
            {

                check = model.addata(model);
            }

            if (check > 0)
            {
                return RedirectToAction("Index");

            }
            return RedirectToAction("create", model);
        }

        public ActionResult Duplicate(string Name, Int32 ID)
        {
            string json = "";
            var list = new GLUser().checkDuplicate(ID, Name);
            if (list.Count() > 0)
            {
                json = " Duplicate Record Found ";
            }
            return Json(JsonConvert.SerializeObject(json), JsonRequestBehavior.AllowGet);
        }

        private DataTable loadrighta()
        {
            string[] userdata = new Login().userinfofromCookie();
            DataTable dtright = new Login().checkRightUser(" where GLUser.Userid='" + userdata[1] + "' and UserForms.Formid='19' ");
            return dtright;
        }
    }
}

SAGERPNEW2018/Views/GLUser/Index.cshtml
@model AdmissionSystemModel.AdmissionModel.GLUser

@{
    ViewBag.Title = "Search User";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div id="modals"></div>

<header class="page-header">
    <h2>User Information</h2>

    <div class="right-wrapper pull-right">
        <ol class="breadcrumbs">
            <li>
                <a href="index.html">
                    <i class="fa fa-home"></i>
                </a>
            </li>
            <li><span>Setup</span></li>
            <li><span>User Information</span></li>
        </ol>

        <a class="sidebar-right-toggle" data-open="sidebar-right"><i class="fa fa-chevron-left"></i></a>
    </div>
</header>

<!-- start: page -->
<section class="panel">
    <header class="panel-heading">
        <div class="panel-actions">
            <a href="#" class="fa fa-caret-down"></a>
            <a href="#" class="fa fa-times"></a>
        </div>

        <h2 class="panel-title">All User Information Data</h2>
    </header>
    <div class="panel-body">
        <div class="row">
            <div class="col-sm-6">
                <div class="mb-md">
                    @if (Model.IsNew)
                    {
                        <button type="button" id="Add" onclick="add()" class="btn btn-primary"> <i class="fa fa-plus"></i> Add New</button>
                        @* <button type="button" id="cancelll" onclick="window.history.back()" class="btn btn-primary">Cancel</button>*@
                    }

                </div>
            </div>
        </div>
        <table class="table table-bordered table-striped mb-none table-hover" id="UserTable">
            <thead>
                <tr>
                    <th >User Name</th>
                    <th >Group </th>
                    <th >Status </th>
                    <th width="100px">Actions</th>
                </tr>
            </thead>

            <tbody id="ProductTableID">
                @foreach (var item in Model.getAllUserdata())
                {
                    <tr>
                        <td> @item.UserName </td>
                        <td> @item.GroupTitle </td>

                        @if (@item.Active)
                        {
                            <td>InActive </td>

                        }
                        else
                        {

                            <td>Active </td>


                        }
                        <td>
                            @if (Convert.ToBoolean(Model.Isedit))
                            {

                                <a href="#basicEdit" class="on-default edit-row mb-xs mt-xs mr-xs modal-with-zoom-anim" title="Edit" onclick="Edit(@item.Userid)">
                                    <i class="fa fa-pencil"></i>

                                </a>
                            }
                            @if (Convert.ToBoolean(Model.Isdelete))
                            {
                                <a href="#basic" class="on-default edit-row mb-xs mt-xs mr-xs modal-with-zoom-anim" title="Delete"  onclick="Del(@item.Userid)">
                                    <i class="glyphicon glyphicon-trash"></i>

                                </a>
                            }
                            <a href="#" class="on-default edit-row" title="View" onclick="view(@item.Userid)">
                                <i class="fa fa-table"></i>

                            </a>
                            @*<button class="btn btn-success btn-xs" onclick="view(@item["Voucherid"])"><span class="glyphicon glyphicon-blackboard"></span> View</button>*@
                        </td>

                    </tr>
                }
            </tbody>

        </table>
    </div>

</section>


<script>

    $(document).ready(function () {
        //$('#btnTriggerEdit').click();
        $("#modals").load('/CustomClasses/IndexModaling.html')


            $("#UserTable").dataTable(
               {
                   "aoColumns": [{ "bSearchable": true }, { "bSearchable": true }, { "bSearchable": true },
                       { "bSearchable": false }],
                   "bSort": true,

                   dom: 'Bfrtip',
                   buttons: [
                              {
                                  extend: 'copy',
                                  text: '<span class="glyphicon glyphicon-floppy-disk"></span><span><strong> Copy</strong></span>',
                                  className: 'btn btn-primary  btn-sm',

                                  title: 'User Information',

                                  exportOptions: {
                                      columns: ':visible'
                                  }

                              },

                            {
                                extend: 'pdf',
                                text: '  <span class="glyphicon glyphicon-file"></span><span> PDF</strong></span>',
                                className: 'btn btn-primary  btn-sm',
                                title: 'User Information',
                                orientation: 'portrait',
                                pageSize: 'A4',
                                exportOptions: {
                                    columns: ':visible'
                                },

                                customize: function (doc) {

                                    doc.styles.title = {
                                        color: 'red',
                                        fontSize: '40',
                                        // background: 'blue',
                                        alignment: 'center'
                                    }
                                },



                            },

                             {

                                 title: 'User Information',
                                 text: '<span class="glyphicon glyphicon-th"></span><span><strong> Excel</strong></span>',
                                 className: 'btn btn-primary  btn-sm',
                                 orientation: 'portrait',
                                 pageSize: 'A4',
                                 extend: 'excel',
                                 footer: true,
                                 exportOptions: {
                                     columns: ':visible'
                                 }
                             },


                           {
                               extend: 'csv',

                               title: 'User Information',
                               text: '<span class="	glyphicon glyphicon-list-alt"></span><span><strong> CSV</strong></span>',
                               className: 'btn btn-primary  btn-sm',
                               exportOptions: {
                                   columns: ':visible'
                               }

                           },
                         {
                             extend: 'print',
                             title: 'User Information',
                             text: '<span class="glyphicon glyphicon-print"></span><span><strong> Print</strong></span>',
                             className: 'btn btn-primary  btn-sm',

                             exportOptions: { columns: ':visible' }

                         },
                         {

                             extend: 'colvis',
                             text: '<span class="glyphicon glyphicon-blackboard"></span><span><strong> Column visibility</strong></span>',
                             className: 'btn btn-primary  btn-sm',

                             //  'colvis'
                         }

                   ],
                   columnDefs: [{ targets: -1, visible: true }]
                   //paging: false
               })
            var a = '@TempData["Dependancy"]'
            if (a != "") {
                $("#basicDendent").modal('show');
            }
        })

        function add() {
            window.location.href = "/GLUser/create/"
        }

        var EditID = 0;
        var DeleteID = 0;
        function confirmPopupEdit()
        {
            window.location.href = "/GLUser/Edit/" + EditID + "|1"
        }

        function Edit(id) {
            EditID=id
        }

        function confirmPopupDelete() {
            window.location.href = "/GLUser/delete/" + DeleteID

        }
        function Del(id) {
            DeleteID = id
        }

        function view(id) {
            window.location.href = "/GLUser/Edit/" + id + "|0"

        }

</script>

SAGERPNEW2018/Views/GLUser/create.cshtml
@model AdmissionSystemModel.AdmissionModel.GLUser

@{
    ViewBag.Title = "User";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@using (@Html.BeginForm("Save", "GLUser", FormMethod.Post, new { @id = "myform" }))
{
    if (Model.Userid > 0)
    {
        ViewBag.Title = "User Edit";

    }
    else
    {

        ViewBag.Title = "User Create";

    }
    @Html.HiddenFor(m => m.Userid)
    <header class="page-header">
        <h2>GL User</h2>

        <div class="right-wrapper pull-right">
            <ol class="breadcrumbs">
                <li>
                    <a href="index.html">
                        <i class="fa fa-home"></i>
                    </a>
                </li>
                <li><span>Setup</span></li>
                <li><span>GL User</span></li>
            </ol>

            <a class="sidebar-right-toggle" data-open="sidebar-right"><i class="fa fa-chevron-left"></i></a>
        </div>
    </header>


    <div class="panel">
        <!-- start: page -->
        <div class="row">
            <div class="col-md-12">


                <section class="panel">
                    <header class="panel-heading">
                        <div class="panel-actions">
                            <a href="#" class="fa fa-caret-down"></a>
                            <a href="#" class="fa fa-times"></a>
                        </div>

                        <h2 class="panel-title">GL User</h2>
                        <p class="panel-subtitle">
                            Form control for input GL User data .
                        </p>
                    </header>
                    <div class="panel-body">
                       
                        <div class="row">
                            <div class="col-md-6">
                                <label>User Name:</label>&nbsp;<span style="color:red;" class="error-span" id="ShortTitleIDError"></span>
                                @Html.TextBoxFor(model => model.UserName, new { @placeholder = "Enter User Name", @class = "form-control" })
                            </div>

                            <div class="col-md-6">
                                <label>User Password:</label>&nbsp;<span style="color:red;" class="error-span" id="ShortTitleIDError"></span>
                                @Html.TextBoxFor(model => model.UserPassword, new { type = "password", @placeholder = "Enter Password", @class = "form-control" })

                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-6">
                                <label>Type:</label>&nbsp;<span style="color:red;" class="error-span" id="TitleIDError"></span>
                                @Html.DropDownListFor(model => model.GroupID, Model.loadUsergroup(), new { @placeholder = "Enter Type", @class = "form-control selectpicker " })

                            </div>
                            <div class="col-md-4">
                                <div style="margin-top: 30px;" class="form-check">
                                    @Html.CheckBoxFor(model => model.Active, new { })
                                    <label for="Active">InActive</label>
                                </div>
                            </div>


                        </div>


                    </div>
                    <footer class="panel-footer">
                        <div class="row">
                            <div class="col-sm-9">
                                <button type="button" onclick="postform()" class="btn btn-primary">Save</button>
                                <button type="button" id="cancelll" class="btn btn-default" onclick="window.history.back()">Cancel</button>
                            </div>
                        </div>
                    </footer>
                </section>

            </div>

        </div>

    </div>

}





<script>
    function postform() {

        var ReturnValue = true

        if ($("#GroupID").val() == "0") {
            $('#GroupID').selectpicker('setStyle', 'btn-danger');
            $('#GroupID').selectpicker('refresh');

            ReturnValue = false;
            $("#TypeID").focus();
        }
        if ($("#UserName").val() == "") {
            $('#UserName').css('border-color', 'red');
            $("#UserName").focus();

            ReturnValue = false;

        }

        if ($("#UserPassword").val() == "") {
            $('#UserPassword').css('border-color', 'red');
            $("#UserPassword").focus();

            ReturnValue = false;

        }

        if (ReturnValue) {
            $("#myform").submit();

        }

        var Data = { Name: $('#UserName').val(), ID: $("#Userid").val() }
        $.ajax({
            async: false,
            url: "/GLUser/Duplicate",
            data: Data,
            success: function (data) {

                var c =JSON.parse(data);
                if (c!="") {
                    alert(c)
                    ReturnValue = false;
                }
            },
            error: function () {
                ReturnValue = false;
                alert("Error")
            }
        })


    }
    $(document).ready(function () {
       // $('#Myform :input').select()

        $('.selectpicker').selectpicker('selectAll');

        if ('@Model.IsView' == 'True') {
            $('#myform :input').attr('disabled', true);
            $('#cancelll').attr('disabled', false);

        }

    });


</script>